import React, { useEffect, useRef, useState } from 'react';
import { images } from '../data/images.generated';

type NativeImgProps = Omit<
  React.ImgHTMLAttributes<HTMLImageElement>,
  'src' | 'srcSet' | 'sizes' | 'width' | 'height' | 'loading' | 'alt'
>;

interface OptimizedImageProps extends NativeImgProps {
  /** Path of the original inside `images-src/`, e.g. "weddings/photo.jpg". */
  src: string;
  /**
   * How wide the image is rendered, so the browser can pick the right file.
   * Remember that with `object-cover` the rendered width can exceed the box width.
   */
  sizes: string;
  alt: string;
  /** Above-the-fold image: load eagerly with high fetch priority. */
  priority?: boolean;
  /** Must match the `object-fit` of the image so the placeholder lines up. */
  placeholderFit?: 'cover' | 'contain';
  /** Must match the `object-position` of the image (CSS value). */
  placeholderPosition?: string;
}

const BASE = import.meta.env.BASE_URL;

/** Percent-encode spaces etc. — srcset is whitespace/comma separated. */
const url = (p: string) => BASE + encodeURI(p).replace(/,/g, '%2C');

const srcSetFor = (path: string, widths: number[], ext: string) =>
  widths.map((w) => `${url(`${path}-${w}.${ext}`)} ${w}w`).join(', ');

/**
 * Gaussian-blurred SVG wrapper around the tiny base64 preview, so the
 * placeholder looks like a soft photo instead of a pixelated thumbnail.
 */
const blurredPlaceholder = (dataUri: string, w: number, h: number) => {
  const vw = 800; // arbitrary virtual canvas; stdDeviation below is relative to it
  const vh = Math.round((vw * h) / w);
  const svg =
    `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${vw} ${vh}'>` +
    `<filter id='b' color-interpolation-filters='sRGB'><feGaussianBlur stdDeviation='20'/>` +
    `<feComponentTransfer><feFuncA type='discrete' tableValues='1 1'/></feComponentTransfer></filter>` +
    `<image width='100%' height='100%' preserveAspectRatio='none' filter='url(#b)' href='${dataUri}'/></svg>`;
  return `url("data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}")`;
};

/**
 * Responsive, lazy-loaded image served as AVIF → WebP → JPEG/PNG via <picture>,
 * with a blurred placeholder shown until the real image has loaded.
 *
 * Variants are generated by `npm run images` (scripts/optimize-images.mjs).
 */
const OptimizedImage: React.FC<OptimizedImageProps> = ({
  src,
  sizes,
  alt,
  priority = false,
  placeholderFit = 'cover',
  placeholderPosition = 'center',
  style,
  onLoad,
  ...rest
}) => {
  const entry = images[src];
  const imgRef = useRef<HTMLImageElement>(null);
  const [loaded, setLoaded] = useState(false);

  // Cached images can finish loading before React attaches `onLoad`.
  useEffect(() => {
    if (imgRef.current?.complete) setLoaded(true);
  }, []);

  if (!entry) {
    if (import.meta.env.DEV) {
      console.warn(`[OptimizedImage] "${src}" not found. Add it to images-src/ and run "npm run images".`);
    }
    return null;
  }

  const { path, widths, width, height, fallback, placeholder } = entry;

  const placeholderStyle: React.CSSProperties =
    placeholder && !loaded
      ? {
          backgroundImage: blurredPlaceholder(placeholder, width, height),
          backgroundSize: placeholderFit,
          backgroundPosition: placeholderPosition,
          backgroundRepeat: 'no-repeat',
        }
      : {};

  return (
    <picture>
      <source type="image/avif" srcSet={srcSetFor(path, widths, 'avif')} sizes={sizes} />
      <source type="image/webp" srcSet={srcSetFor(path, widths, 'webp')} sizes={sizes} />
      <img
        ref={imgRef}
        src={url(`${path}-${widths[Math.min(widths.length - 1, 2)]}.${fallback}`)}
        srcSet={srcSetFor(path, widths, fallback)}
        sizes={sizes}
        width={width}
        height={height}
        alt={alt}
        loading={priority ? 'eager' : 'lazy'}
        fetchPriority={priority ? 'high' : 'auto'}
        decoding={priority ? 'sync' : 'async'}
        style={{ ...placeholderStyle, ...style }}
        onLoad={(e) => {
          setLoaded(true);
          onLoad?.(e);
        }}
        {...rest}
      />
    </picture>
  );
};

export default OptimizedImage;
