// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run `npm run images` after adding/replacing photos in images-src/.

export interface ImageEntry {
  /** Public path without width/extension, e.g. "images/weddings/photo". */
  path: string;
  /** Width of the largest generated variant. */
  width: number;
  /** Height of the largest generated variant. */
  height: number;
  /** All generated widths (ascending). */
  widths: number[];
  /** Fallback format for browsers without AVIF/WebP. */
  fallback: 'jpg' | 'png';
  /** Tiny base64 WebP used as a blurred placeholder while loading. */
  placeholder?: string;
}

export const images: Record<string, ImageEntry> = {
  "backgrounds/castelbrando.jpeg": {
    "path": "images/backgrounds/castelbrando",
    "width": 960,
    "height": 640,
    "widths": [
      480,
      768,
      960
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBACdASoUAA0APtFUo0uoJKMhsAgBABoJbACdMoACEXGLYix88hnMgADh+MkWWFtTCiTt0FX88N0k2U9GELQ5HEuTy8m7wLmUHQOBYRM2WnUUQctqTjSsGtVQ4oOdXJII6yHG0B/nrVEQxlsxPc+9UyZhSpSOgGevJ/sBGAzef2X7XN83jAAA"
  },
  "backgrounds/faq-floral.png": {
    "path": "images/backgrounds/faq-floral",
    "width": 1024,
    "height": 1024,
    "widths": [
      480,
      768,
      1024
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQBACdASoUABQAPtFWpk0oJCOiMBgIAQAaCWcAxNgWiVzdDNDlCDkYYAD+8XREM4yGATJ/U2+86T2sAptkKAXPSvSfYc1Z3hS35sAA"
  },
  "backgrounds/hero-bg.jpg": {
    "path": "images/backgrounds/hero-bg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      768,
      1280,
      1920
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACQBACdASoUAA0APtFUo0uoJKMhsAgBABoJQBOgUzme6GKKYh0qGHW2aaPNj3AA/i84QGlHFRlwlkb9OkptOTdlVwdi2kLgf6xjNOjOX51w/+6fRou/6pde1ap6LJgpzOYzrrZZACckqovdjge8Im+FLzd6B6/WbG3OG0ULBK6E82EwRMoL6bPFd3sqi05tI201cVyctUyuvZk6XAAAAA=="
  },
  "backgrounds/WhatsApp Image 2026-04-24 at 23.26.21.jpeg": {
    "path": "images/backgrounds/WhatsApp Image 2026-04-24 at 23.26.21",
    "width": 1736,
    "height": 1736,
    "widths": [
      480,
      768,
      1280,
      1736
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAAAwBQCdASoUABQAPtFcpU6oJSMiKAqpABoJZAC06Yx2dFhMtAsWyQTHZwK0Ti8FaEYMgAD+7wMTQGzb/HY0hyN04tMa9EJ9uyb9ObRtE1D6asiy0C2C/uoknH2bPk4D3ri5ya78p3u8W3YQe/hfVtoTyl3OeISSbKs5EhpL16CyfnYrTYukHp0HkxeFgi7bUEU68weipeDrG7on4dVhukXy4MJeUO6oqh0T0DIA"
  },
  "events/1000324931.jpg": {
    "path": "images/events/1000324931",
    "width": 1920,
    "height": 1282,
    "widths": [
      480,
      768,
      1280,
      1920
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoUAA0APtFUo0uoJKMhsAgBABoJQBOmUABsKSm/f5ms3yNAAP7hU5sYf+X/BvjRG2oUUwaeOZSwg1gJuBvjDA41Oiq2ag/5KEZyO98DBDSM6TMHAQN2HnisbRu7A1VF1R3YOLxbkQ1tdnFK8XUx5yAX3JLCuUsDlyFv1ATbKKynoc+VNP1aFDHXSAA="
  },
  "events/1000324938.jpg": {
    "path": "images/events/1000324938",
    "width": 1920,
    "height": 1282,
    "widths": [
      480,
      768,
      1280,
      1920
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoUAA0APtFUo0uoJKMhsAgBABoJYwCdMoAC/JO/PjFBNNmTAAD+kbelAb3O0xk7M7CG24FwZRlxfb3cCZcMQFic3D06jRLxuCTi2ggddIPFrXW8qiDtrOfF+Dnkj46PWMLtJrc8oq3VvBlEhy3hjUJCmgJ5/Zp3X0IYNAbVc1wakjBrlbopUAAA"
  },
  "events/FB_IMG_1773166900952.jpg": {
    "path": "images/events/FB_IMG_1773166900952",
    "width": 1080,
    "height": 1350,
    "widths": [
      480,
      768,
      1080
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRuYAAABXRUJQVlA4INoAAAAQBQCdASoUABkAPtFcp04oJSOiKAqpABoJQBOkHoAgF6W6keBm/5oQWa3pr6fL9ZmgAP7v4PV+kM0kmwj74SpI+kop0ggqPUgPGcEXbR3SKxXXbIv0+SB0bX7GJi+Axkv/kZznY0e/2Lz9DwPU/uB40DXUZYQxaPkld0WHJ2brPUkPuG6rI85WZVKH9xqMKc9WI49bH0q0ka4ydAEFvGJvguPB2DR2glnTh8xL577wkk+ffuC4VbWeMmfDP5IGlUVP7nWAClOsEJeqAkPG0AHHAEFwAUMANqUAAA=="
  },
  "events/IMG-20250921-WA0023.jpg": {
    "path": "images/events/IMG-20250921-WA0023",
    "width": 1200,
    "height": 1600,
    "widths": [
      480,
      768,
      1200
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRhYBAABXRUJQVlA4IAoBAADwBQCdASoUABsAPslSnkunpKKhsAwA8BkJbAC7MoFWVteFj8DmkvSdMnzjrgg/a9tRuLgHT3nmgAD+8KRpVjQ1y30Zd3Neo8ucgHr2DAgozjc4UL1Q/E86mFtoArZHvA5O8XlymEY2umaJWrfNhkuTcdaoefyzWZoXB/KisLebPqcJ7l2KrHdPGNk3N4/sHHAX/wSSaZv9BnSdTEhQyKqTmWEVnfStlKcXqTiBy8qYYCg60Zn5Z84z9L2hm23i8sySRtFgEzIp9WzXlmxHwIbczh+260A6ZYZYHBBgzmB4gt6D8qfcZm1ZYaM5rZmpVbsVNjOkycemw/Z/jzSIVRJHK5TDNEflkgAAAA=="
  },
  "events/Primavera P.co'25-1.jpg": {
    "path": "images/events/Primavera P.co'25-1",
    "width": 1500,
    "height": 1000,
    "widths": [
      480,
      768,
      1280,
      1500
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADQAwCdASoUAA0APtFUo0uoJKMhsAgBABoJagCdMoADQqMtnX4VDfQA/siEinPK3t7epme5P2w7d3nHchPnxsr4zKbwTFq48FlCePbrgn8XQWSeC4RzEo8vLWSlGxk/EeDT0d88JexzMTJEKZWW8sfuXllezahFknbjriyFKKxJg6RS1yaaK/BfpbLVEan4AAA="
  },
  "events/Primavera P.co'25-7.jpg": {
    "path": "images/events/Primavera P.co'25-7",
    "width": 1500,
    "height": 1000,
    "widths": [
      480,
      768,
      1280,
      1500
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACwBACdASoUAA0APtFUo0uoJKMhsAgBABoJbACdMoMYA0f9wTrTjIDTjpOGRELgAP5zGh4tAfLTCusLWvAwGzZeqz6k9YUVdc75IUgggy+Dw6+ut/KXWXzJ+aQB+wIo4PxGXIDHO5G02mQVO5ds0kf1+IMJJkt4x+2bp3oEVyUf6o8PCOEFfk3Tw3B+x21WLE1Tx4TgyvI5u00yeh0EALMoRcrl9FwPAAA="
  },
  "tour_leader/IMG-20240919-WA0016.jpg": {
    "path": "images/tour_leader/IMG-20240919-WA0016",
    "width": 1640,
    "height": 1232,
    "widths": [
      480,
      768,
      1280,
      1640
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAADQBACdASoUAA8APtFUo0uoJKMhsAgBABoJZACdIIpJtl2CMBEnuXBf3lywDFbDKAD+IOOhLkW9FiR1RzY4feUgdJi06Un2uuVxwkt/e24fCbKErAD2vy/BV3hzQlIFw7cnumgcpzSsA0o7IwMFmy6PEKdPL9Gwizhrm9wG024CgGY0ZsM2xcKQlHNmO3oyQ2klDR0Y6pj2POz9R/pWHeRRhb08WBuBr8AAAA=="
  },
  "tour_leader/IMG-20251214-WA0020.jpg": {
    "path": "images/tour_leader/IMG-20251214-WA0020",
    "width": 1200,
    "height": 1600,
    "widths": [
      480,
      768,
      1200
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRjABAABXRUJQVlA4ICQBAAAwBgCdASoUABsAPtFap04oJSOiKAqpABoJagCdL4Bs1S7mSTd2w0kHTg1Bz37/D9aWZTVIyK34ZcAAAP6b5Fn1/bJQkwOVeKG692wX2ocOALShf+2Wf6AscMaiEmNUNmKtEJQVVdb8SHS1HsPLY1nTvF1UcxcBVSdfyy1QFCb4eyDbQhjFKpPQdgyODM6fknMUn6doCtpO4vNVr/6D9rffzWWdh8dRE4E8l03I8SvdMS3wl0UPmUjVW6ogBVG3ZF7RsL2gS85a3IMxWWVXGYEBttRRjlu+rjwTkHhP0iKpWwBvf7bgSLA6XTP7YThOrWpWRFy7v6SnXokyX/sTCbVPKdKt9FMfuzrtf/zd2iX+TC/dd///ivz6bNe5DSf7344ewAAA"
  },
  "tour_leader/PXL_20260426_145033654.jpg": {
    "path": "images/tour_leader/PXL_20260426_145033654",
    "width": 1920,
    "height": 1442,
    "widths": [
      480,
      768,
      1280,
      1920
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAADQBACdASoUAA8APtFUo0uoJKMhsAgBABoJZACdMoMusYADk6lYW3I/q41uhQVQAAD1ndw4hBXntmJt57eANWoDWDq4DFrwTyQozoVnYGJYtOVDBfZHUVYOxmJag3LTKDKTGtH3lQjxe3+IQHN7UnC18/Jz+gpKop0bUNPCqTC+2x5V20p+1gv8yFVfE213EZFUR9WhSPyIAdoO3M+UChhJgLpQQN4YtYItmWQ5tjqeWzUhiKFiz+8YvOoAAA=="
  },
  "weddings/14 Damiano 85mm -16 settembre 2023.jpg": {
    "path": "images/weddings/14 Damiano 85mm -16 settembre 2023",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      768,
      1280,
      1920
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBACdASoUAA0APtFUo0uoJKMhsAgBABoJYgCdMoMxgEPror55z3dN/embLgD+5uUgaw+7bK0va1V4BAC3lV6Ns4ZHx0w/wZzW4nyzsW3E2TlZzbKtVisGRiemGkeXJ/JWXYFU1F7Iextq7BU+qW9mJNw/7g6kHHmkxHBmiG8LQwTAQ2nWxGf7VgbEyKHQi+2635aB5xsigUA6gAA="
  },
  "weddings/290 Damiano 28 75mm-16 settembre 2023.jpg": {
    "path": "images/weddings/290 Damiano 28 75mm-16 settembre 2023",
    "width": 1920,
    "height": 1440,
    "widths": [
      480,
      768,
      1280,
      1920
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBACdASoUAA8APtFUo0uoJKMhsAgBABoJQBOmUAXoAZwXFQGoel4tOwAA/u+dDQ5O7w8F4UjxixD/towGD0QK0v3DqaYn4kKubKS3OtaO37jpzYmbYE+dYz9MTlmgAZ6ERfLrpO65xd4SGTIPL06t+5925k9mMcX/e58jD8Gfsq2bVgHcJ5ta5CX0guJ5/j5GjZE8R8kbP3mPWBXAAA=="
  },
  "weddings/76 Damiano 85mm -16 settembre 2023.jpg": {
    "path": "images/weddings/76 Damiano 85mm -16 settembre 2023",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      768,
      1280,
      1920
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACQBACdASoUAA0APtFUo0uoJKMhsAgBABoJQBOgUzme6GKKYh0qGHW2aaPNj3AA/i84QGlHFRlwlkb9OkptOTdlVwdi2kLgf6xjNOjOX51w/+6fRou/6pde1ap6LJgpzOYzrrZZACckqovdjge8Im+FLzd6B6/WbG3OG0ULBK6E82EwRMoL6bPFd3sqi05tI201cVyctUyuvZk6XAAAAA=="
  },
  "weddings/IMG-20250202-WA0025.jpg": {
    "path": "images/weddings/IMG-20250202-WA0025",
    "width": 1143,
    "height": 1600,
    "widths": [
      480,
      768,
      1143
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRv4AAABXRUJQVlA4IPIAAADwBQCdASoUABwAPtFcqU4oJSQiKAqpABoJQBAgk+BK3m58QjV6+mcybW9LJKM9+cTAGukKLwBNQAD+9DJJUjba0fNzmFhyJz4tSjjGUtZhW4sHbgaSRdtRnOCJCZTVRnwzz6mB8mVCpXTboPVYcs0kutkbzD6N8xtHS687Km9BYC8PmsfLm2JYTkOBTndL2iHgbQQ29NMIyQkPjChAhosNdEG0tWhRUU1E8bv1z1Abq0IbcLxE0LRA5ghRcKKZkr6sr1xRBH01yOPohH8m3p8QSCE+25hOlt9YM4JvsVdtIKFOLCtgu202mtnmM0xIUBeAAA=="
  },
  "weddings/IMG-20250202-WA0028.jpg": {
    "path": "images/weddings/IMG-20250202-WA0028",
    "width": 1600,
    "height": 1143,
    "widths": [
      480,
      768,
      1280,
      1600
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoUAA4APtFUo0uoJKMhsAgBABoJQAALytGh5uJLlk3KVGagAP7s0V10lfgYBOZ/rzhnpQdJpqbE6kzTaIxKGP/Uzb3n4e3iVF89ZY763exH576OlB10dOUp/rPlv//0Lj7AMCoP5KAKDLQQehRAAA=="
  },
  "weddings/WhatsApp Image 2026-03-09 at 20.00.10 (1).jpeg": {
    "path": "images/weddings/WhatsApp Image 2026-03-09 at 20.00.10 (1)",
    "width": 1600,
    "height": 1066,
    "widths": [
      480,
      768,
      1280,
      1600
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACwAwCdASoUAA0APtFUo0uoJKMhsAgBABoJaQAAQe/3bmgIEm2NQAD+0DvVhb77cLzleD65bZWGZ+6JABzEm6KfJ0cSapV9R93iH9NR0U0JmbpLRpgPwaTWP/2/mCvgHmCtRw+DsiKpO9Nk/muWPr1FD4dwfBrcJc7F23+/wSnKkNvFSPIoAA=="
  },
  "weddings/WhatsApp Image 2026-03-09 at 20.00.10 (4).jpeg": {
    "path": "images/weddings/WhatsApp Image 2026-03-09 at 20.00.10 (4)",
    "width": 1600,
    "height": 1066,
    "widths": [
      480,
      768,
      1280,
      1600
    ],
    "fallback": "jpg",
    "placeholder": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBACdASoUAA0APtFUo0uoJKMhsAgBABoJbAC06YvWyDhCU0xxf4JHgAD+TNLr7+wom93GdEP2ZEd5u5E1WG2fyjrl+LDxOnSJo0M0+lDbxjDBpCMEB7mPwvrYJ3tlNf4nlnm1m10zt0wN9BPvwQ8qyZdjQR6qh/yVaSOeHExrWp0b271rMm9HuJUtQsIGYVzyoKDAAAA="
  }
};

/** Above-the-fold image preloaded in index.html (keep Hero in sync via this constant). */
export const PRELOAD_IMAGE = {
  "key": "backgrounds/hero-bg.jpg",
  "sizes": "(max-aspect-ratio: 3/2) 210vh, 140vw"
} as const;
